import { ImageResponse } from '@vercel/og';
import { NextRequest } from 'next/server';

export const runtime = 'edge';

// --- ROBUST FONT LOADER ---
async function loadGoogleFont(font: string, text: string) {
  const url = `https://fonts.googleapis.com/css2?family=${font}:wght@700&text=${encodeURIComponent(text)}`;
  const css = await (await fetch(url)).text();
  const resource = css.match(/src: url\((.+)\) format\('(opentype|truetype)'\)/);
  
  if (resource) {
    const response = await fetch(resource[1]);
    if (response.status == 200) {
      return await response.arrayBuffer();
    }
  }
  throw new Error('Failed to load font data');
}

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);

    const topic = searchParams.get('topic')?.slice(0, 50) || 'Unknown Topic';
    const winner = searchParams.get('winner')?.slice(0, 30) || 'Undecided';
    const criticalBlow = searchParams.get('blow')?.slice(0, 140) || 'No closing argument recorded.';
    
    const fontData = await loadGoogleFont('Inter', topic + winner + criticalBlow + 'DEBATE WRAPPED VICTORY GOES TO The Critical Blow Generated by DebateArena.ai');

    return new ImageResponse(
      (
        <div
          style={{
            height: '100%',
            width: '100%',
            display: 'flex',
            flexDirection: 'column',
            backgroundColor: '#020617', // Hex for slate-950
            color: 'white',
            padding: '40px',
            position: 'relative',
            fontFamily: 'Inter',
            overflow: 'hidden',
          }}
        >
           {/* Background Gradient Orbs - Using explicit CSS for safety */}
          <div style={{
            position: 'absolute',
            top: '-200px',
            left: '-100px',
            width: '500px',
            height: '500px',
            backgroundColor: '#9333ea', // purple-600
            opacity: 0.2,
            borderRadius: '100%',
            filter: 'blur(80px)', // Standard CSS filter
          }} />
          <div style={{
            position: 'absolute',
            bottom: '-100px',
            right: '-100px',
            width: '400px',
            height: '400px',
            backgroundColor: '#2563eb', // blue-600
            opacity: 0.2,
            borderRadius: '100%',
            filter: 'blur(80px)',
          }} />
          
          {/* HEADER */}
          <div style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            width: '100%',
            borderBottom: '1px solid #1e293b', // slate-800
            paddingBottom: '20px',
            marginBottom: '40px',
            zIndex: 10, // Must be a number
          }}>
            <div style={{ display: 'flex', alignItems: 'center' }}>
               {/* Logo Square */}
              <div style={{
                width: '32px',
                height: '32px',
                marginRight: '12px',
                borderRadius: '6px',
                backgroundImage: 'linear-gradient(to top right, #facc15, #f97316)', // yellow to orange
              }}></div>
              <span style={{ fontSize: '20px', fontWeight: 700, color: '#cbd5e1', letterSpacing: '0.05em' }}>
                DEBATE WRAPPED
              </span>
            </div>
            <div style={{
              padding: '6px 16px',
              backgroundColor: '#1e293b',
              borderRadius: '9999px',
              fontSize: '14px',
              color: '#94a3b8',
              textTransform: 'uppercase',
              letterSpacing: '0.1em',
            }}>
              {topic}
            </div>
          </div>

          {/* MAIN CONTENT HERO */}
          <div style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            flexGrow: 1,
            zIndex: 10,
          }}>
            <span style={{
              fontSize: '24px',
              color: '#60a5fa', // blue-400
              fontWeight: 700,
              letterSpacing: '0.2em', // Fixed arbitrary value
              marginBottom: '10px',
              textTransform: 'uppercase',
            }}>
              VICTORY GOES TO
            </span>
            {/* Gradient Text for Winner */}
            <h1 style={{
              fontSize: '80px',
              fontWeight: 900,
              textAlign: 'center',
              lineHeight: 1.1,
              margin: 0,
              backgroundImage: 'linear-gradient(to right, #fde047, #fb923c, #ef4444)', // yellow-orange-red
              backgroundClip: 'text',
              color: 'transparent',
              textShadow: '0 10px 30px rgba(0,0,0,0.5)',
            }}>
              {winner.toUpperCase()}
            </h1>
          </div>

          {/* THE CRITICAL BLOW CARD */}
          <div style={{
            display: 'flex',
            flexDirection: 'column',
            backgroundColor: 'rgba(15, 23, 42, 0.6)', // slate-900 with opacity
            border: '1px solid rgba(51, 65, 85, 0.5)', // slate-700
            padding: '30px',
            borderRadius: '20px',
            marginTop: '40px',
            zIndex: 10,
            position: 'relative',
            boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
          }}>
             <div style={{
               position: 'absolute',
               top: '-20px',
               left: '30px',
               fontSize: '60px',
               color: '#334155', // slate-700
               lineHeight: 1,
             }}>“</div>
             
            <span style={{
              fontSize: '14px',
              color: '#64748b', // slate-500
              fontWeight: 700,
              textTransform: 'uppercase',
              marginBottom: '10px',
              marginLeft: '30px',
            }}>
              The Critical Blow
            </span>
            <blockquote style={{
              fontSize: '28px',
              color: '#f1f5f9', // slate-100
              lineHeight: 1.4,
              marginLeft: '20px',
              borderLeft: '4px solid #f97316', // orange-500
              paddingLeft: '20px',
              fontWeight: 500,
            }}>
              "{criticalBlow}"
            </blockquote>
          </div>

           {/* FOOTER */}
           <div style={{
             position: 'absolute',
             bottom: '20px',
             right: '30px',
             color: '#475569', // slate-600
             fontSize: '14px',
             fontWeight: 700,
             zIndex: 10,
           }}>
              Generated by DebateArena.ai
           </div>
        </div>
      ),
      {
        width: 1200,
        height: 630,
        fonts: [
          {
            name: 'Inter',
            data: fontData,
            style: 'normal',
            weight: 700,
          },
        ],
      },
    );
  } catch (e: any) {
    console.error(`OG Image Error: ${e.message}`);
    return new Response(`Failed to generate image`, {
      status: 500,
    });
  }
}